import Head from "next/head";
import Link from "next/link";
import React from "react";
import MockHousing from "~/component/mock";

export default function Home() {
  return (
    <>
      <Head>
        <title>BayGate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Jersey+25&family=Quicksand:wght@300..700&display=swap" rel="stylesheet" />
      </Head>
      <main className="w-full h-full bg-white">
        <div className="fixed top-0 left-0 right-0 xl:px-16 px-10 z-50 h-40 py-5 bg-white flex flex-col justify-center gap-2 shadow-md">
          <div className="w-full flex justify-between items-center mb-3 mt-10">
            <h1 className="text-3xl border-double border-4 border-black py-1 pl-2 pr-1 tracking-[0.2em] font-medium" style={{ fontFamily: "quicksand"}}>B|A|Y|G|A|T|E</h1>
            <div className="flex gap-6">
              <Link href="/login">
                <button className="relative h-12 overflow-hidden rounded-md border border-neutral-400 bg-transparent px-6 text-neutral-950 before:absolute before:bottom-0 before:left-0 before:block before:h-full before:w-full before:-translate-x-full before:bg-neutral-100 before:transition-transform hover:before:translate-x-0"><span className="relative">
                  Log in
                </span>
                </button>
              </Link>
              <Link href="/signup">
                <button className="group relative inline-flex h-12 items-center justify-center overflow-hidden rounded-md border border-neutral-400 bg-transparent px-6 font-medium text-neutral-600 transition-all duration-100 [box-shadow:5px_5px_rgb(82_82_82)] active:translate-x-[3px] active:translate-y-[3px] active:[box-shadow:0px_0px_rgb(82_82_82)]">
                  Sign up
                </button>
              </Link>
            </div>
          </div>
          <div className="w-full pt-3 gap-8 flex justify-end">
            <button role="link" className="relative after:absolute after:bottom-0 after:left-0 after:right-0 after:h-[2px] after:w-full after:origin-bottom after:scale-x-0 after:bg-neutral-800 after:transition-transform after:duration-300 after:ease-[cubic-bezier(0.65_0.05_0.36_1)] hover:after:origin-bottom hover:after:scale-x-100">
              Sort
            </button>
            <button role="link" className="relative after:absolute after:bottom-0 after:left-0 after:right-0 after:h-[2px] after:w-full after:origin-bottom after:scale-x-0 after:bg-neutral-800 after:transition-transform after:duration-300 after:ease-[cubic-bezier(0.65_0.05_0.36_1)] hover:after:origin-bottom hover:after:scale-x-100">
              Filter
            </button>
          </div>
        </div>

        <div className="pt-56 pb-10 xl:px-16 px-10 w-full h-full">
          <div className="grid 2xl:gap-10 gap-4 xl:grid-cols-4 md:grid-cols-3 sm:grid-cols-2 grid-cols-1">
            <MockHousing />
          </div>
        </div>
        {/* add a div for footer */}
        {/* <div className="w-full h-20 bg-neutral-800 text-neutral-50 flex justify-center items-center">
          <p>Nice2Home</p>
        </div> */}
      </main>
    </>
  );
}
